fixed_values = {
    "COMISION": 0.28,
    "AHORRO_MANO_DE_OBRA_NORMAL": 0.25,
    "CUOTA_FIJA_NORMAL": 5.72,
    "CUOTA_VARIABLE_MENOS_14": 0,
    "CUOTA_VARIABLE_14_20": 0.75,
    "CUOTA_VARIABLE_MAS_20": 2.5,
    "DERECHO_CONEXION": 400,
    "EMPTY_DERECHO_CONEXION": 0,
    "MORA": 1,
}
