# -*- mode: ruby -*-
# vi: set ft=ruby :

# Function to check whether VM was already provisioned
# https://stackoverflow.com/a/38203497/930271
def provisioned?(vm_name='default', provider='virtualbox')
    File.exist?(".vagrant/machines/#{vm_name}/#{provider}/action_provision")
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20200407.0.0"
  config.vm.box_check_update = false

  if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :machine
      config.cache.auto_detect = false
      config.cache.enable :apt
      config.cache.enable :apt_lists
      # config.cache.enable :npm
      # config.cache.enable :pip
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
      # Disable it if problems with shared folders or guest additions appears
      # or if you want to speed up `vagrant up` a bit
      config.vbguest.auto_update = true
  end

  config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1512"
  end

  config.vm.provision "shell", path:"bootstrap.sh"
end
